name: wakatime update

on:
  # for manual workflow trigger
  workflow_dispatch:
  schedule:
    - cron: "30 11 * * *"

jobs:
  update-readme:
    name: WakaReadme DevMetrics
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master # this action name
        with:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          CODE_LANG: go
          COMMIT_MESSAGE: update(waka) incoming new stats
          SHOW_TITLE: true
          LANG_COUNT: 10

